name: Terraform Apply

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checks out your GitHub repository

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5 # Adjust the version as needed

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Replace with your desired AWS region

      - name: Terraform Init
        id: terraform_init
        run: terraform init

      - name: Terraform Format
<<<<<<< HEAD
        run: terraform fmt
=======
        run: terraform fmt -check  # Checks if the format is correct
>>>>>>> 8865154ffca43f6d93689bab0979439d14451d7d

      - name: Terraform Plan
        if: steps.terraform_init.outcome == 'success'  # Runs only if init is successful
        run: terraform plan

      - name: Terraform Apply
        if: steps.terraform_init.outcome == 'success'  # Runs only if init is successful
        run: terraform apply -auto-approve
